// <auto-generated />
using System;
using CrossvilleCoed.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Capstone.Migrations
{
    [DbContext(typeof(CrossvilleCoedDbContext))]
    partial class CrossvilleCoedDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CrossvilleCoed.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("GameTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("integer");

                    b.Property<int>("VisitorTeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("VisitorTeamId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GameTime = new DateTime(2023, 10, 2, 18, 15, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 1,
                            VisitorTeamId = 2
                        },
                        new
                        {
                            Id = 2,
                            GameTime = new DateTime(2023, 10, 5, 19, 15, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 2,
                            VisitorTeamId = 1
                        },
                        new
                        {
                            Id = 3,
                            GameTime = new DateTime(2023, 10, 9, 18, 15, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 1,
                            VisitorTeamId = 2
                        },
                        new
                        {
                            Id = 4,
                            GameTime = new DateTime(2023, 10, 12, 19, 15, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 2,
                            VisitorTeamId = 1
                        });
                });

            modelBuilder.Entity("CrossvilleCoed.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PositionId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Trenton",
                            LastName = "Guffey",
                            PositionId = 1,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Ethan",
                            LastName = "Todd",
                            PositionId = 6,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Tyler",
                            LastName = "Richardson",
                            PositionId = 7,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Camie",
                            LastName = "Miller",
                            PositionId = 7,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "John aka Paco",
                            LastName = "Rolan",
                            PositionId = 1,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "Jonathan",
                            LastName = "Stout",
                            PositionId = 5,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 7,
                            FirstName = "Karli",
                            LastName = "Threet",
                            PositionId = 3,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 8,
                            FirstName = "Riley",
                            LastName = "Norris",
                            PositionId = 7,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "Scottie",
                            LastName = "Payne",
                            PositionId = 2,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 10,
                            FirstName = "Tori",
                            LastName = "Stout",
                            PositionId = 4,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 11,
                            FirstName = "Chandler",
                            LastName = "Hardwick",
                            PositionId = 7,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 12,
                            FirstName = "Jade",
                            LastName = "Payne",
                            PositionId = 4,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 13,
                            FirstName = "Chance",
                            LastName = "Clark",
                            PositionId = 1,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 14,
                            FirstName = "Wayne",
                            LastName = "Burns",
                            PositionId = 1,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 15,
                            FirstName = "Justin",
                            LastName = "Timmons",
                            PositionId = 6,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 16,
                            FirstName = "Russell",
                            LastName = "Campbell",
                            PositionId = 7,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 17,
                            FirstName = "Dora",
                            LastName = "Erazocordova",
                            PositionId = 2,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 18,
                            FirstName = "Destiny",
                            LastName = "Ruppe",
                            PositionId = 7,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 19,
                            FirstName = "Brent",
                            LastName = "Bowman",
                            PositionId = 1,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 20,
                            FirstName = "Jessica",
                            LastName = "Lancianese",
                            PositionId = 3,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 21,
                            FirstName = "Kendall",
                            LastName = "Cooper",
                            PositionId = 7,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 22,
                            FirstName = "Nick",
                            LastName = "Bowman",
                            PositionId = 5,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 23,
                            FirstName = "Chris",
                            LastName = "Patton",
                            PositionId = 5,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 24,
                            FirstName = "Christa",
                            LastName = "Wendig",
                            PositionId = 4,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 25,
                            FirstName = "Joseph",
                            LastName = "Haley",
                            PositionId = 7,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 26,
                            FirstName = "Justin",
                            LastName = "Carr",
                            PositionId = 7,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 27,
                            FirstName = "Tanner",
                            LastName = "Hurd",
                            PositionId = 7,
                            TeamId = 2
                        });
                });

            modelBuilder.Entity("CrossvilleCoed.Models.PlayerGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Double")
                        .HasColumnType("integer");

                    b.Property<int>("FieldersChoice")
                        .HasColumnType("integer");

                    b.Property<int>("GameId")
                        .HasColumnType("integer");

                    b.Property<int>("HomeRun")
                        .HasColumnType("integer");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("RunsBattedIn")
                        .HasColumnType("integer");

                    b.Property<int>("RunsScored")
                        .HasColumnType("integer");

                    b.Property<int>("Sacrifice")
                        .HasColumnType("integer");

                    b.Property<int>("Single")
                        .HasColumnType("integer");

                    b.Property<double>("TotalPlateAppearances")
                        .HasColumnType("double precision");

                    b.Property<int>("Triple")
                        .HasColumnType("integer");

                    b.Property<int>("Walk")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerGames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Double = 2,
                            FieldersChoice = 0,
                            GameId = 1,
                            HomeRun = 0,
                            PlayerId = 15,
                            RunsBattedIn = 2,
                            RunsScored = 4,
                            Sacrifice = 0,
                            Single = 2,
                            TotalPlateAppearances = 4.0,
                            Triple = 0,
                            Walk = 0
                        },
                        new
                        {
                            Id = 2,
                            Double = 2,
                            FieldersChoice = 0,
                            GameId = 1,
                            HomeRun = 1,
                            PlayerId = 25,
                            RunsBattedIn = 3,
                            RunsScored = 4,
                            Sacrifice = 0,
                            Single = 2,
                            TotalPlateAppearances = 4.0,
                            Triple = 0,
                            Walk = 0
                        },
                        new
                        {
                            Id = 3,
                            Double = 0,
                            FieldersChoice = 0,
                            GameId = 1,
                            HomeRun = 1,
                            PlayerId = 22,
                            RunsBattedIn = 3,
                            RunsScored = 3,
                            Sacrifice = 0,
                            Single = 2,
                            TotalPlateAppearances = 4.0,
                            Triple = 0,
                            Walk = 0
                        },
                        new
                        {
                            Id = 4,
                            Double = 0,
                            FieldersChoice = 0,
                            GameId = 1,
                            HomeRun = 0,
                            PlayerId = 24,
                            RunsBattedIn = 2,
                            RunsScored = 2,
                            Sacrifice = 0,
                            Single = 2,
                            TotalPlateAppearances = 4.0,
                            Triple = 0,
                            Walk = 0
                        },
                        new
                        {
                            Id = 5,
                            Double = 0,
                            FieldersChoice = 0,
                            GameId = 1,
                            HomeRun = 1,
                            PlayerId = 23,
                            RunsBattedIn = 3,
                            RunsScored = 3,
                            Sacrifice = 0,
                            Single = 2,
                            TotalPlateAppearances = 4.0,
                            Triple = 0,
                            Walk = 0
                        },
                        new
                        {
                            Id = 6,
                            Double = 0,
                            FieldersChoice = 0,
                            GameId = 1,
                            HomeRun = 0,
                            PlayerId = 18,
                            RunsBattedIn = 1,
                            RunsScored = 2,
                            Sacrifice = 0,
                            Single = 2,
                            TotalPlateAppearances = 4.0,
                            Triple = 0,
                            Walk = 0
                        },
                        new
                        {
                            Id = 7,
                            Double = 2,
                            FieldersChoice = 0,
                            GameId = 1,
                            HomeRun = 0,
                            PlayerId = 19,
                            RunsBattedIn = 3,
                            RunsScored = 1,
                            Sacrifice = 0,
                            Single = 1,
                            TotalPlateAppearances = 4.0,
                            Triple = 0,
                            Walk = 0
                        },
                        new
                        {
                            Id = 8,
                            Double = 1,
                            FieldersChoice = 0,
                            GameId = 1,
                            HomeRun = 0,
                            PlayerId = 26,
                            RunsBattedIn = 1,
                            RunsScored = 1,
                            Sacrifice = 0,
                            Single = 1,
                            TotalPlateAppearances = 3.0,
                            Triple = 0,
                            Walk = 0
                        },
                        new
                        {
                            Id = 9,
                            Double = 0,
                            FieldersChoice = 0,
                            GameId = 1,
                            HomeRun = 0,
                            PlayerId = 17,
                            RunsBattedIn = 1,
                            RunsScored = 0,
                            Sacrifice = 0,
                            Single = 1,
                            TotalPlateAppearances = 3.0,
                            Triple = 0,
                            Walk = 0
                        },
                        new
                        {
                            Id = 10,
                            Double = 0,
                            FieldersChoice = 0,
                            GameId = 1,
                            HomeRun = 0,
                            PlayerId = 14,
                            RunsBattedIn = 3,
                            RunsScored = 2,
                            Sacrifice = 0,
                            Single = 2,
                            TotalPlateAppearances = 3.0,
                            Triple = 0,
                            Walk = 0
                        },
                        new
                        {
                            Id = 11,
                            Double = 2,
                            FieldersChoice = 0,
                            GameId = 1,
                            HomeRun = 0,
                            PlayerId = 3,
                            RunsBattedIn = 2,
                            RunsScored = 3,
                            Sacrifice = 0,
                            Single = 2,
                            TotalPlateAppearances = 3.0,
                            Triple = 0,
                            Walk = 0
                        },
                        new
                        {
                            Id = 12,
                            Double = 0,
                            FieldersChoice = 1,
                            GameId = 1,
                            HomeRun = 0,
                            PlayerId = 7,
                            RunsBattedIn = 0,
                            RunsScored = 2,
                            Sacrifice = 0,
                            Single = 1,
                            TotalPlateAppearances = 4.0,
                            Triple = 0,
                            Walk = 1
                        },
                        new
                        {
                            Id = 13,
                            Double = 0,
                            FieldersChoice = 0,
                            GameId = 1,
                            HomeRun = 0,
                            PlayerId = 2,
                            RunsBattedIn = 2,
                            RunsScored = 1,
                            Sacrifice = 0,
                            Single = 0,
                            TotalPlateAppearances = 4.0,
                            Triple = 1,
                            Walk = 0
                        },
                        new
                        {
                            Id = 14,
                            Double = 2,
                            FieldersChoice = 0,
                            GameId = 1,
                            HomeRun = 0,
                            PlayerId = 8,
                            RunsBattedIn = 4,
                            RunsScored = 2,
                            Sacrifice = 0,
                            Single = 0,
                            TotalPlateAppearances = 4.0,
                            Triple = 1,
                            Walk = 0
                        },
                        new
                        {
                            Id = 15,
                            Double = 1,
                            FieldersChoice = 0,
                            GameId = 1,
                            HomeRun = 0,
                            PlayerId = 10,
                            RunsBattedIn = 2,
                            RunsScored = 1,
                            Sacrifice = 0,
                            Single = 2,
                            TotalPlateAppearances = 4.0,
                            Triple = 0,
                            Walk = 0
                        },
                        new
                        {
                            Id = 16,
                            Double = 0,
                            FieldersChoice = 1,
                            GameId = 1,
                            HomeRun = 0,
                            PlayerId = 9,
                            RunsBattedIn = 1,
                            RunsScored = 1,
                            Sacrifice = 0,
                            Single = 2,
                            TotalPlateAppearances = 4.0,
                            Triple = 0,
                            Walk = 0
                        },
                        new
                        {
                            Id = 17,
                            Double = 0,
                            FieldersChoice = 0,
                            GameId = 1,
                            HomeRun = 0,
                            PlayerId = 1,
                            RunsBattedIn = 1,
                            RunsScored = 1,
                            Sacrifice = 0,
                            Single = 3,
                            TotalPlateAppearances = 4.0,
                            Triple = 0,
                            Walk = 0
                        },
                        new
                        {
                            Id = 18,
                            Double = 1,
                            FieldersChoice = 0,
                            GameId = 1,
                            HomeRun = 0,
                            PlayerId = 4,
                            RunsBattedIn = 1,
                            RunsScored = 1,
                            Sacrifice = 0,
                            Single = 0,
                            TotalPlateAppearances = 4.0,
                            Triple = 0,
                            Walk = 0
                        },
                        new
                        {
                            Id = 19,
                            Double = 1,
                            FieldersChoice = 0,
                            GameId = 1,
                            HomeRun = 2,
                            PlayerId = 5,
                            RunsBattedIn = 4,
                            RunsScored = 3,
                            Sacrifice = 0,
                            Single = 0,
                            TotalPlateAppearances = 4.0,
                            Triple = 0,
                            Walk = 0
                        },
                        new
                        {
                            Id = 20,
                            Double = 2,
                            FieldersChoice = 0,
                            GameId = 1,
                            HomeRun = 0,
                            PlayerId = 11,
                            RunsBattedIn = 2,
                            RunsScored = 3,
                            Sacrifice = 0,
                            Single = 1,
                            TotalPlateAppearances = 3.0,
                            Triple = 0,
                            Walk = 0
                        },
                        new
                        {
                            Id = 21,
                            Double = 0,
                            FieldersChoice = 0,
                            GameId = 1,
                            HomeRun = 1,
                            PlayerId = 6,
                            RunsBattedIn = 2,
                            RunsScored = 2,
                            Sacrifice = 0,
                            Single = 2,
                            TotalPlateAppearances = 3.0,
                            Triple = 0,
                            Walk = 0
                        },
                        new
                        {
                            Id = 22,
                            Double = 2,
                            FieldersChoice = 0,
                            GameId = 2,
                            HomeRun = 0,
                            PlayerId = 15,
                            RunsBattedIn = 2,
                            RunsScored = 2,
                            Sacrifice = 0,
                            Single = 2,
                            TotalPlateAppearances = 4.0,
                            Triple = 0,
                            Walk = 0
                        },
                        new
                        {
                            Id = 23,
                            Double = 2,
                            FieldersChoice = 0,
                            GameId = 2,
                            HomeRun = 1,
                            PlayerId = 25,
                            RunsBattedIn = 3,
                            RunsScored = 4,
                            Sacrifice = 0,
                            Single = 1,
                            TotalPlateAppearances = 4.0,
                            Triple = 0,
                            Walk = 0
                        },
                        new
                        {
                            Id = 24,
                            Double = 0,
                            FieldersChoice = 0,
                            GameId = 2,
                            HomeRun = 2,
                            PlayerId = 22,
                            RunsBattedIn = 3,
                            RunsScored = 4,
                            Sacrifice = 0,
                            Single = 2,
                            TotalPlateAppearances = 4.0,
                            Triple = 0,
                            Walk = 0
                        },
                        new
                        {
                            Id = 25,
                            Double = 0,
                            FieldersChoice = 0,
                            GameId = 2,
                            HomeRun = 0,
                            PlayerId = 24,
                            RunsBattedIn = 2,
                            RunsScored = 3,
                            Sacrifice = 0,
                            Single = 2,
                            TotalPlateAppearances = 4.0,
                            Triple = 0,
                            Walk = 0
                        },
                        new
                        {
                            Id = 26,
                            Double = 0,
                            FieldersChoice = 0,
                            GameId = 2,
                            HomeRun = 1,
                            PlayerId = 23,
                            RunsBattedIn = 3,
                            RunsScored = 3,
                            Sacrifice = 0,
                            Single = 2,
                            TotalPlateAppearances = 4.0,
                            Triple = 0,
                            Walk = 0
                        },
                        new
                        {
                            Id = 27,
                            Double = 0,
                            FieldersChoice = 0,
                            GameId = 2,
                            HomeRun = 0,
                            PlayerId = 18,
                            RunsBattedIn = 2,
                            RunsScored = 2,
                            Sacrifice = 0,
                            Single = 2,
                            TotalPlateAppearances = 4.0,
                            Triple = 0,
                            Walk = 0
                        },
                        new
                        {
                            Id = 28,
                            Double = 0,
                            FieldersChoice = 0,
                            GameId = 2,
                            HomeRun = 0,
                            PlayerId = 19,
                            RunsBattedIn = 3,
                            RunsScored = 3,
                            Sacrifice = 0,
                            Single = 2,
                            TotalPlateAppearances = 4.0,
                            Triple = 0,
                            Walk = 0
                        },
                        new
                        {
                            Id = 29,
                            Double = 0,
                            FieldersChoice = 0,
                            GameId = 2,
                            HomeRun = 0,
                            PlayerId = 26,
                            RunsBattedIn = 2,
                            RunsScored = 2,
                            Sacrifice = 0,
                            Single = 2,
                            TotalPlateAppearances = 3.0,
                            Triple = 0,
                            Walk = 0
                        },
                        new
                        {
                            Id = 30,
                            Double = 0,
                            FieldersChoice = 0,
                            GameId = 2,
                            HomeRun = 0,
                            PlayerId = 17,
                            RunsBattedIn = 1,
                            RunsScored = 0,
                            Sacrifice = 0,
                            Single = 1,
                            TotalPlateAppearances = 3.0,
                            Triple = 0,
                            Walk = 0
                        },
                        new
                        {
                            Id = 31,
                            Double = 0,
                            FieldersChoice = 0,
                            GameId = 2,
                            HomeRun = 0,
                            PlayerId = 14,
                            RunsBattedIn = 3,
                            RunsScored = 2,
                            Sacrifice = 0,
                            Single = 2,
                            TotalPlateAppearances = 3.0,
                            Triple = 0,
                            Walk = 0
                        },
                        new
                        {
                            Id = 32,
                            Double = 2,
                            FieldersChoice = 0,
                            GameId = 2,
                            HomeRun = 0,
                            PlayerId = 3,
                            RunsBattedIn = 2,
                            RunsScored = 3,
                            Sacrifice = 0,
                            Single = 2,
                            TotalPlateAppearances = 4.0,
                            Triple = 0,
                            Walk = 0
                        },
                        new
                        {
                            Id = 33,
                            Double = 0,
                            FieldersChoice = 0,
                            GameId = 2,
                            HomeRun = 0,
                            PlayerId = 7,
                            RunsBattedIn = 0,
                            RunsScored = 1,
                            Sacrifice = 0,
                            Single = 1,
                            TotalPlateAppearances = 4.0,
                            Triple = 0,
                            Walk = 3
                        },
                        new
                        {
                            Id = 34,
                            Double = 0,
                            FieldersChoice = 0,
                            GameId = 2,
                            HomeRun = 0,
                            PlayerId = 2,
                            RunsBattedIn = 1,
                            RunsScored = 1,
                            Sacrifice = 0,
                            Single = 0,
                            TotalPlateAppearances = 4.0,
                            Triple = 1,
                            Walk = 0
                        },
                        new
                        {
                            Id = 35,
                            Double = 2,
                            FieldersChoice = 0,
                            GameId = 2,
                            HomeRun = 0,
                            PlayerId = 8,
                            RunsBattedIn = 4,
                            RunsScored = 2,
                            Sacrifice = 0,
                            Single = 0,
                            TotalPlateAppearances = 4.0,
                            Triple = 1,
                            Walk = 0
                        },
                        new
                        {
                            Id = 36,
                            Double = 1,
                            FieldersChoice = 0,
                            GameId = 2,
                            HomeRun = 0,
                            PlayerId = 10,
                            RunsBattedIn = 2,
                            RunsScored = 1,
                            Sacrifice = 0,
                            Single = 2,
                            TotalPlateAppearances = 4.0,
                            Triple = 0,
                            Walk = 0
                        },
                        new
                        {
                            Id = 37,
                            Double = 0,
                            FieldersChoice = 0,
                            GameId = 2,
                            HomeRun = 1,
                            PlayerId = 1,
                            RunsBattedIn = 1,
                            RunsScored = 1,
                            Sacrifice = 0,
                            Single = 3,
                            TotalPlateAppearances = 4.0,
                            Triple = 0,
                            Walk = 0
                        },
                        new
                        {
                            Id = 38,
                            Double = 1,
                            FieldersChoice = 0,
                            GameId = 2,
                            HomeRun = 0,
                            PlayerId = 4,
                            RunsBattedIn = 1,
                            RunsScored = 1,
                            Sacrifice = 0,
                            Single = 0,
                            TotalPlateAppearances = 4.0,
                            Triple = 0,
                            Walk = 0
                        },
                        new
                        {
                            Id = 39,
                            Double = 1,
                            FieldersChoice = 0,
                            GameId = 2,
                            HomeRun = 2,
                            PlayerId = 5,
                            RunsBattedIn = 4,
                            RunsScored = 3,
                            Sacrifice = 0,
                            Single = 0,
                            TotalPlateAppearances = 4.0,
                            Triple = 0,
                            Walk = 0
                        },
                        new
                        {
                            Id = 40,
                            Double = 2,
                            FieldersChoice = 0,
                            GameId = 2,
                            HomeRun = 0,
                            PlayerId = 11,
                            RunsBattedIn = 2,
                            RunsScored = 3,
                            Sacrifice = 0,
                            Single = 1,
                            TotalPlateAppearances = 3.0,
                            Triple = 0,
                            Walk = 0
                        },
                        new
                        {
                            Id = 41,
                            Double = 0,
                            FieldersChoice = 0,
                            GameId = 2,
                            HomeRun = 1,
                            PlayerId = 6,
                            RunsBattedIn = 2,
                            RunsScored = 3,
                            Sacrifice = 0,
                            Single = 2,
                            TotalPlateAppearances = 3.0,
                            Triple = 0,
                            Walk = 0
                        });
                });

            modelBuilder.Entity("CrossvilleCoed.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Pos")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Pos = "P"
                        },
                        new
                        {
                            Id = 2,
                            Pos = "C"
                        },
                        new
                        {
                            Id = 3,
                            Pos = "1B"
                        },
                        new
                        {
                            Id = 4,
                            Pos = "2B"
                        },
                        new
                        {
                            Id = 5,
                            Pos = "3B"
                        },
                        new
                        {
                            Id = 6,
                            Pos = "SS"
                        },
                        new
                        {
                            Id = 7,
                            Pos = "OF"
                        },
                        new
                        {
                            Id = 8,
                            Pos = "EH"
                        });
                });

            modelBuilder.Entity("CrossvilleCoed.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fair Oaks Farms",
                            UserProfileId = 2
                        },
                        new
                        {
                            Id = 2,
                            Name = "Campbells Pest Control",
                            UserProfileId = 3
                        });
                });

            modelBuilder.Entity("CrossvilleCoed.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Trenton",
                            IdentityUserId = "dbc40bc6-0829-4ac5-a3ed-180f5e916a5f",
                            LastName = "Guffey"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Camie",
                            IdentityUserId = "01ccfa71-2781-48bf-8e35-196e48859662",
                            LastName = "Miller"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Wayne",
                            IdentityUserId = "4eeea886-15a8-46d0-a26b-57ed40a5ee0a",
                            LastName = "Burns"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "c3aaeb97-d2ba-4a53-a521-4eea61e59b35",
                            Name = "Admin",
                            NormalizedName = "admin"
                        },
                        new
                        {
                            Id = "1d373bd0-c738-40ee-bff1-b135b40a7be9",
                            Name = "Coach",
                            NormalizedName = "coach"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "dbc40bc6-0829-4ac5-a3ed-180f5e916a5f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "28d5d196-d7df-47d7-9a44-9928a389c350",
                            Email = "tjguffey50@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEOaInbx3pX1Kh9kh3VrjIZZ92PijQIVMdllXpeJilFryjl0MQYrSTEK9N82dL7QfyQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4321f44c-9c4d-449a-afea-3278d966e888",
                            TwoFactorEnabled = false,
                            UserName = "Administrator"
                        },
                        new
                        {
                            Id = "01ccfa71-2781-48bf-8e35-196e48859662",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "dedf6179-99dc-4640-b0b8-dd5aa8b71b17",
                            Email = "Camie.Miller@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEHBwdvUpD2Ol7WFtGpzKrnDdeybcNzy2kKQqnm9JJAj+/SpnToDil7Lbicj+OcZs3Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "de65b1d4-c560-4585-8168-9feb99b141d6",
                            TwoFactorEnabled = false,
                            UserName = "FairOaksFarms"
                        },
                        new
                        {
                            Id = "4eeea886-15a8-46d0-a26b-57ed40a5ee0a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d696831a-6bf6-484f-a598-aca99181fbf4",
                            Email = "Wayne.Burns@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEMrcQQbE5HoplPfWSOGIJosFbfN8uIPJCCN0ogLH36ABdJSU4P9xsEWZ8inqR0NWPw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bc12e288-a57a-43d6-bce5-1127753fa9ac",
                            TwoFactorEnabled = false,
                            UserName = "CampbellsPestControl"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "dbc40bc6-0829-4ac5-a3ed-180f5e916a5f",
                            RoleId = "c3aaeb97-d2ba-4a53-a521-4eea61e59b35"
                        },
                        new
                        {
                            UserId = "01ccfa71-2781-48bf-8e35-196e48859662",
                            RoleId = "1d373bd0-c738-40ee-bff1-b135b40a7be9"
                        },
                        new
                        {
                            UserId = "4eeea886-15a8-46d0-a26b-57ed40a5ee0a",
                            RoleId = "1d373bd0-c738-40ee-bff1-b135b40a7be9"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CrossvilleCoed.Models.Game", b =>
                {
                    b.HasOne("CrossvilleCoed.Models.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrossvilleCoed.Models.Team", "VisitorTeam")
                        .WithMany()
                        .HasForeignKey("VisitorTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HomeTeam");

                    b.Navigation("VisitorTeam");
                });

            modelBuilder.Entity("CrossvilleCoed.Models.Player", b =>
                {
                    b.HasOne("CrossvilleCoed.Models.Position", "Pos")
                        .WithMany()
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrossvilleCoed.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pos");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("CrossvilleCoed.Models.PlayerGame", b =>
                {
                    b.HasOne("CrossvilleCoed.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CrossvilleCoed.Models.Player", "Player")
                        .WithMany("PlayerGames")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("CrossvilleCoed.Models.Team", b =>
                {
                    b.HasOne("CrossvilleCoed.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("CrossvilleCoed.Models.UserProfile", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CrossvilleCoed.Models.Player", b =>
                {
                    b.Navigation("PlayerGames");
                });
#pragma warning restore 612, 618
        }
    }
}
